<?php
echo FILTER_FLAG_QUERY_REQUIRED . '<br>';
echo FILTER_FLAG_PATH_REQUIRED . '<br>';
echo FILTER_FLAG_QUERY_REQUIRED | FILTER_FLAG_PATH_REQUIRED . '<br>';
echo 0 | FILTER_FLAG_QUERY_REQUIRED | FILTER_FLAG_PATH_REQUIRED . '<br>';


$array = array(FILTER_FLAG_QUERY_REQUIRED,FILTER_FLAG_PATH_REQUIRED);
echo array_sum($array);
